
name: Create New post

on:
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [create-new-post]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Retrive all posts and build sites, then upload under '/public'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello, world
        shell: bash
        run: echo "Hello, world"