# This is a basic workflow to help you get started with Actions
name: Build Hugo on Docker

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to build site with Hugo on docker
    steps:
      # get sources
      - name: Checkout
        uses: actions/checkout@v2

      # run build docker
      - name: Build
        uses: ./build/actions/build-and-deploy
        with:
          who-to-greet: 'Mona the Octocat'
      
      # get output
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"