# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Retrive all posts and build sites, then upload under '/public' and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      # retrive all posts and generate posts for Hugo
      - name: Retrive and generate posts
        shell: bash
        run: python3 ./scripts/retrive_and_generate_posts.py
        env:
          ENDPOINT: ${{secrets.ENDPOINT}}
          X_API_KEY: ${{secrets.X_API_KEY}}
          OUTPUT: ./content/posts

      - name: Build with Hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          version: 0.79.0
          image: ext-alpine

      # deploy artifactto netlify
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v1.2.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'public'
